Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/03/2022
Var
  nome, endereco: caracter
Inicio
  nome := "Cristian"
  endereco := "Saudades SC"
  escreval ("O usuário de crack ", nome, " mora em ", endereco)

Fimalgoritmo