Algoritmo "loop PARA - FOR"
// PARA {1} DE {2} ATE {3} FACA
//    {4}
//  FIMPARA
//  {1 - variavel contadora}
//  {2 - numero inicial do loop}
//  {3 - numero final do loop}
//  {4 - instruções para cada interação}
Var
  numero : inteiro
  contador : inteiro
Inicio
  escreva ("Digite o número a exibir loop: ")
  leia (numero)
  para contador de 0 ate numero passo 10 faca
    escreval ("O número percorrido é: ", contador)
  fimpara

fimalgoritmo