Algoritmo "0001 - Function"
// Declarada após as variaveis
// Posso criar var dentro da funcao para ser usada somente na funcao
Var
    num, a, b : real
funcao <nome-de-funcao> (<parametros>) : <tipo-de-dado>

  funcao somar(a, b: real): real
  var

  Inicio
    retorne a+b
  fimfuncao

Inicio

  num : somar(1.1, 2.2)
  escreval(num)
Fimalgoritmo                                    .