Algoritmo "Exercicio"
Var
   nome : caracter
   idade : inteiro
   altura : real
   maioridade : logico
inicio
  escreva("Qual o seu nome?")
  leia(nome)
  escreva("Qual sua idade?")
  leia(idade)
  escreva("Qual sua altura?")
  leia(altura)
  maioridade := idade >= 18
  limpatela
  
  escreval("Nome: " + nome)
  escreval("Idade: " , idade)
  escreval("Altura: " , altura)
  escreval("É de maior? " , maioridade)
  
Fimalgoritmo